name: Analyze Internal Links

on:
  push:
    paths:
      - "articles/**"
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в полночь

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установка зависимостей
        run: pip install numpy scikit-learn

      - name: Запуск анализа
        run: python analyze_links.py

      - name: Коммит обновлений
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add internal_links.json
          git commit -m "Обновление внутренних ссылок"
          git push
